spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/linklens}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:kHushi1@6}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

jwt.secret=ReplaceThisWithAVeryLongRandomSecretKeyForDevelopment123456789
jwt.expiration=86400000

server.address=0.0.0.0
app.base-url=${APP_BASE_URL:http://localhost:8081}
geo.api.base-url=http://ip-api.com/json



# ==========================
# Google OAuth2
# ==========================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_Ccd ~/LinkLensLIENT_SECRET}

spring.ai.google.genai.api-key=${SPRING_AI_GOOGLE_GENAI_API_KEY}

spring.security.oauth2.client.registration.google.scope=openid,profile,email

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

app.rate-limit.max-requests=20
app.rate-limit.window-seconds=60


spring.ai.google.genai.chat.options.model=gemini-3-flash-preview

logging.level.org.springframework.security=TRACE